providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true

ports:
  websecure:
    tls:
      enabled: true # IMPORTANT WHEN USING EXTERNAL SERVICES/ENDPOINTS

ingressClass:
  enabled: true
  isDefaultClass: true

additionalArguments:
- "--serverstransport.insecureskipverify=true"