# netmaker
---
kind: Secret
apiVersion: v1
metadata:
  name: netmaker-nm-secret
  namespace: my-netmaker
type: Opaque
stringData:
  MASTER_KEY: REPLACE_MASTER_KEY

# netmaker-mq
---
apiVersion: v1
kind: Secret
metadata:
  name: netmaker-mq-secret
  namespace: my-netmaker
type: Opaque
stringData:
  MQ_PASSWORD: REPLACE_MQ_PASSWORD