## seafile-db
---
kind: Secret
apiVersion: v1
metadata:
  name: seafile-db-secret
  namespace: my-seafile
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: CHANGEME

## seafile-app
---
kind: Secret
apiVersion: v1
metadata:
  name: seafile-app-secret
  namespace: my-seafile
type: Opaque
stringData:
  DB_ROOT_PASSWD: CHANGEME
  SEAFILE_ADMIN_PASSWORD: CHANGEME

# Use secrets for things which are actually secret like API keys, credentials, etc
# Base64 encode the values stored in a Kubernetes Secret: $ pbpaste | base64 | pbcopy
# The --decode flag is convenient: $ pbpaste | base64 --decode
# apiVersion: v1
# kind: Secret
# metadata:
#   name: env-secrets
# type: Opaque
# data:
#   DB_PASSWORD: cDZbUGVXeU5e0ZW
#   REDIS_PASSWORD: AAZbUGVXeU5e0ZB