version: "3.4"

services:
  netclient:
    network_mode: host
    privileged: true
    restart: always
    environment:
      - TOKEN=$TOKEN
    volumes:
      - '/etc/netclient:/etc/netclient'
    container_name: netclient
    image: 'gravitl/netclient:latest'
