baseDomain: nm.local.127.0.0.1.sslip.io
RWXStorageClassName: longhorn # must support RWX
# Default values for netmaker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- number of netmaker server replicas to create
replicas: 3

# -- pod security contect to add
podSecurityContext: {}
# fsGroup: 2000

ui:
  # -- how many UI replicas to create
  replicas: 2

mq:
  # -- how many MQTT replicas to create
  replicas: 2
  singlenode: false
  storageSize: 128Mi
  password: 3yyerWGdds43yegGR

dns:
  # -- whether or not to deploy coredns
  enabled: false
  storageSize: 128Mi

ingress:
  # -- attempts to configure ingress if true
  enabled: true
  tls:
    enabled: false
    issuerName: "letsencrypt-prod"
  annotations:
    ui: {}
    rest: {}
    mq: {}
    base:
      # -- annotation to generate ACME certs if available
      kubernetes.io/ingress.allow-http: "false"
    tls:
      # -- use acme cert if available
      kubernetes.io/tls-acme: "true"
    nginx:
      # -- Redirect http to https
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
      # -- destination addr for route
      nginx.ingress.kubernetes.io/rewrite-target: /
    traefik:
      # -- Redirect to https
      traefik.ingress.kubernetes.io/redirect-entry-point: https
      # -- Redirect to https permanently
      traefik.ingress.kubernetes.io/redirect-permanent: "true"
      # -- rule type
      traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
  hostPrefix:
    # -- ui route subdomain
    ui: 'dashboard.'
    # -- api (REST) route subdomain
    rest: 'api.'
    # -- mqtt route subdomain
    broker: 'broker.'

wireguard:
  # -- whether or not to use WireGuard on server
  enabled: true
  service:
    annotations: {}
    serviceType: NodePort
  # -- whether or not to use Kernel WG (should be false unless WireGuard is installed on hosts).
  kernel: false
  # -- max number of networks that Netmaker will support if running with WireGuard enabled
  networkLimit: 10

postgresql-ha:
  postgresql:
    # -- postgres user to generate
    username: netmaker
    # -- postgres pass to generate
    password: netmaker
    # -- postgress db to generate
    database: netmaker
    # -- postgress number of replicas to deploy
    replicaCount: 2
    enabled: true
  persistence:
    # -- size of postgres DB
    size: 1Gi
