apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: homepage
resources:
- ../../base
configMapGenerator:
- name: homepage
  behavior: merge
  files:
   - files/settings.yaml
   - files/bookmarks.yaml
   - files/services.yaml
patches:
- target:
    name: homepage
    kind: Ingress
  # Enter your public uri
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: myhomepage.20.20.20.20.sslip.io
