background:
  image: https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=2560&q=80
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50

#  providers:
#    longhorn:
#      url: https://longhorn.my.network
