services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    networks:
      - proxy_network
    #ports:
    #  - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockge_data:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.rule=Host(`$PUBLIC_HOSTNAME`)"
      - "traefik.http.routers.dockge.entrypoints=websecure"
      - "traefik.http.services.dockge.loadbalancer.server.port=5001"

volumes:
  dockge_data:

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true
