# app
---
kind: Secret
apiVersion: v1
metadata:
  name: keycloak-app-secret
  namespace: my-keycloak
type: Opaque
stringData:
  KEYCLOAK_PASSWORD: CHANGEME

# db
---
kind: Secret
apiVersion: v1
metadata:
  name: keycloak-db-secret
  namespace: my-keycloak
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: MYSUPERSECRETROOTPWD
  MYSQL_PASSWORD: MYSECRETKEYCLOAKPWD