# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: dashboard-users
# type: kubernetes.io/basic-auth
# data:
#   username: dXNlcg== # echo -n user | base64
#   password: cGFzc3dvcmQ= #  echo -n password | base64

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: dashboard-users
# type: kubernetes.io/basic-auth
# data:
#   users: dXNlcjokYXByMSRSLmxxeHk3SyR3d01HZEkvSm1Zcnh5VTJqT3NxaEIuCgo= # htpasswd -nb user password | openssl base64

---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-secret
  namespace: kube-system
type: kubernetes.io/basic-auth
stringData:
  username: User      # required field for kubernetes.io/basic-auth
  password: TopPassword # required field for kubernetes.io/basic-auth

# echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
# k create secret generic dashboard-users --from-file=users