# ---
# kind: VolumeSnapshotClass
# apiVersion: snapshot.storage.k8s.io/v1
# metadata:
#   name: longhorn-snapshot-vsc
# driver: driver.longhorn.io
# deletionPolicy: Delete
# parameters:
#   type: snap

---
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn-snap
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: snap

---
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn-bak
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: bak

# ---
# kind: VolumeSnapshotClass
# apiVersion: snapshot.storage.k8s.io/v1
# metadata:
#   name: longhorn
# driver: driver.longhorn.io
# deletionPolicy: Delete