version: v3
teleport:
  nodename: teleport-docker-agent
  data_dir: /var/lib/teleport
  join_params:
    token_name: enter_my_join_token
    method: token
  proxy_server: $DOMAINNAME:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: sha256:ffbc....6 # copy ca pin from default agent
  diag_addr: ""

auth_service:
  enabled: "no"

ssh_service:
  enabled: "yes"
  labels:
    customer: my_customer
    platform: docker-agent

proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}

app_service:
  enabled: no
  # enabled: yes
  # apps:
  # - name: "example app"
  #   uri: "http://example-app-url"
      # insecure_skip_verify: true # optionaly
      # public_addr: "mypublicnamewospacesordashes.$DOMAINNAME" # optionaly
      # labels:  # optionaly
      #   customer: dst
      #   app: remotely
      # rewrite:  # optionaly
      #   headers:
      #    - "Host: my.internal.hostname"