---
apiVersion: v1
kind: Secret
metadata:
  name: cf-email
  namespace: cert-manager
type: Opaque
stringData:
  e-mail-address: notifyme@example.com

---
apiVersion: v1
kind: Secret
metadata:
  name: cf-dns-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: your-api-token-with-scopes

---
apiVersion: v1
kind: Secret
metadata:
  name: cf-api-key
  namespace: cert-manager
type: Opaque
stringData:
  api-key: your-api-key-with-global-permissions-bad-idea