## passbolt-db
---
kind: Secret
apiVersion: v1
metadata:
  name: passbolt-db-secret
  namespace: my-passbolt
type: Opaque
stringData:
  MYSQL_PASSWORD: CHANGEME

## passbolt-ce
---
apiVersion: v1
kind: Secret
metadata:
  name: passbolt-ce-secret
  namespace: my-passbolt
type: Opaque
stringData:
  DATASOURCES_DEFAULT_PASSWORD: CHANGEME
  EMAIL_TRANSPORT_DEFAULT_PASSWORD: CHANGEME