version: "3"

services:
  wireguard:
    image: weejewel/wg-easy:latest
    container_name: wg-easy
    restart: unless-stopped
    ports:
      - "$WG_UDP_PORT:$WG_UDP_PORT/udp" # tunnel
      # - "51821:51821/tcp" # ui
    networks:
      - proxy_network
    volumes:
      - wg-easy:/etc/wireguard
    environment:
      # ⚠️ Required:
      - WG_HOST=$PUBLIC_HOSTNAME
      # Optional:
      - PASSWORD=$PASSWORD
      - WG_PORT=$WG_UDP_PORT # 51820
      # - WG_DEFAULT_ADDRESS=$WG_CLIENT_RANGE # 10.8.0.x
      - WG_DEFAULT_DNS=$WG_DEFAULT_DNS # 192.168.0.1,1.1.1.1
      # - WG_MTU=1420
      - WG_ALLOWED_IPS=$WG_DEFAULT_DNS # 192.168.10.0/24,192.168.33.0/24
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wg-easy.rule=Host(`$PUBLIC_HOSTNAME`)"
      - "traefik.http.routers.wg-easy.tls=true"
      - "traefik.http.services.wg-easy.loadbalancer.server.port=51821" # WebUI Port

volumes:
  wg-easy:

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true