version: '3'

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - proxy_network
    # ports:
    # - 8096:8096
    # - 8920:8920 #optional
    # - 7359:7359/udp #optional
    # - 1900:1900/udp #optional
    volumes:
      - jellyfin_config:/config
      - /volume1/video/Serien:/data/tvshows
      - /volume1/video/Filme:/data/movies
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.jellyfin.rule=Host(`$PUBLIC_HOSTNAME`)"
     - "traefik.http.routers.jellyfin.tls=true"
     - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
     # - "traefik.http.routers.traefik.tls.certresolver=letsencrypt" # when using tlsChallenge certresolver

volumes:
  jellyfin_config:

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true