roles: kube,app
authToken: <AUTHTOKEN>
proxyAddr: tp.<DOMAINNAME>:443
kubeClusterName: <CLUSTERNAME>
labels:
    platform: kubernetes
# hostAliases:
# - ip: "1.2.3.4"
#   hostnames:
#     - "tp.<DOMAINNAME>.de"
apps:
- name: placeholder
  uri: http://webapp.my-namespace.svc.cluster.public
# - name: longhorn-oracle
#   uri: http://longhorn-frontend.longhorn-system.svc.cluster.public
#   insecure_skip_verify: yes
#   public_addr: longhornorc.tp.<DOMAINNAME>
# - name: traefik-oracle
#   uri: http://traefik-dashboard.my-traefik.svc.cluster.public:9000/dashboard/#
#   insecure_skip_verify: yes
#   public_addr: traefikorc.tp.<DOMAINNAME>