# db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-ngx-db-cm
  namespace: my-paperless-ngx
data:
  POSTGRES_DB: paperless
  POSTGRES_USER: paperless

# paperless-ngx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-ngx-app-cm
  namespace: my-paperless-ngx
data:
  PAPERLESS_URL: https://paperless.local.127.0.0.1.sslip.io
  PAPERLESS_DBHOST: paperless-ngx-db
  PAPERLESS_OCR_LANGUAGE: deu
  PAPERLESS_REDIS: redis://paperless-ngx-redis:6379
  PAPERLESS_TIME_ZONE: Europe/Berlin
  USERMAP_UID: "1000"
  USERMAP_GID: "1000"
