version: '3'

services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:14
    container_name: teleport
    restart: unless-stopped
    networks:
      - proxy_network
    volumes:
      - /usr/share/teleport/config:/etc/teleport
      - data:/var/lib/teleport
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teleport-https.entrypoints=websecure"
      - "traefik.http.routers.teleport-https.rule=HostRegexp(`$DOMAINNAME`, `{subhost:[a-z]+}.$DOMAINNAME`)"
      - "traefik.http.routers.teleport-https.tls=true"
      - "traefik.http.routers.teleport-https.tls.certresolver=cf-$CF_STAGING_OR_PRODUCTION"
      - "traefik.http.routers.teleport-https.tls.domains[0].main=$DOMAINNAME"
      - "traefik.http.routers.teleport-https.tls.domains[0].sans=*.$DOMAINNAME"
      - "traefik.http.services.teleport.loadbalancer.server.port=3080"
      - "traefik.http.services.teleport.loadbalancer.server.scheme=https"

volumes:
  data:

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true