---
version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    hostname: syncthing #optional
    networks:
      - proxy_network
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    volumes:
      - syncthing_config:/config
      - syncthing_data:/data1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.syncthing.tls=true"
     - "traefik.http.routers.syncthing.rule=Host(`$PUBLIC_HOSTNAME`)"
     - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
     # - "traefik.http.routers.syncthing.tls.certresolver=letsencrypt" # when using tlsChallenge certresolver

volumes:
  syncthing_config:
  syncthing_data:

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true