---
apiVersion: v1
kind: Secret
metadata:
  # name: aws-secret
  name: s3-secret
  namespace: my-longhorn
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: CHANGEME
  AWS_SECRET_ACCESS_KEY: CHANGEME
  AWS_ENDPOINTS: http://S3SERVERNAME:PORT

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   # name: aws-secret
#   name: s3-secret
#   namespace: my-longhorn
# type: Opaque
# data:
#   AWS_ACCESS_KEY_ID: bG9uZ2hvcm4tdGVzdC1hY2Nlc3Mta2V5 # longhorn-test-secret-key | echo -n '<AWS_ACCESS_KEY_ID>' | base64
#   AWS_SECRET_ACCESS_KEY: bG9uZ2hvcm4tdGVzdC1zZWNyZXQta2V5 # longhorn-test-secret-key | echo -n '<AWS_ACCESS_KEY_ID>' | base64
#   AWS_ENDPOINTS: aHR0cHM6Ly9taW5pby1zZXJ2aWNlLmRlZmF1bHQ6OTAwMA== # https://minio-service.default:9000 | echo -n '<AWS_ACCESS_KEY_ID>' | base64

# Backup target C2 cloud: s3://<BUCKETNAME>@eu-001/
# Backup target minio cloud: s3://<BUCKETNAME>@nolocation/