---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: template-pv
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-static
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 100Mi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      # diskSelector: ""
      # nodeSelector: ""
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
    volumeHandle: my-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: template-pvc
  namespace: template-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 100Mi
  volumeName: template-pv