# docker compose run -u --rm root  mssql -- chown -R mssql:root /var/opt/mssql
version: '3.8'
services:
  mssql:
    restart: always
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    networks:
      - proxy_network
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD
      - MSSQL_COLLATION=SQL_Latin1_General_CP1_CI_AS
      - MSSQL_TCP_PORT=$MSSQL_TCP_PORT
      - MSSQL_PID=Developer # Express,Evaluation,Web,Standard,Enterprise,EnterpriseCore
      - MSSQL_MEMORY_LIMIT_MB=$MSSQL_MEMORY_LIMIT_MB
    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log
      - mssql_secrets:/var/opt/mssql/secrets

volumes:
  mssql_data:
  mssql_log:
  mssql_secrets:
  mssql_backup:

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true
