---
apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-ui-cm
  namespace: my-headscale
data:
  TZ: Europe/Berlin
  COLOR: red
  HS_SERVER: "https://hs.local.127.0.0.1.sslip.io"
  DOMAIN_NAME: https://hs.local.127.0.0.1.sslip.io      # The base domain name for this container.
  SCRIPT_NAME: /admin                                   # This is your applications base path (wsgi requires the name "SCRIPT_NAME").  Remove if you are hosing at the root /
  KEY: "1oRrtD8JYdsR0ludbN33mon8IMcG2r8dV0W4EY8n6js="   # Generate with "openssl rand -base64 32" - used to encrypt your key on disk.
  AUTH_TYPE: Basic                                      # AUTH_TYPE is either Basic or OIDC.  Empty for no authentication
  LOG_LEVEL: info                                       # Log level.  "DEBUG", "ERROR", "WARNING", or "INFO".  Default "INFO"
  # ENV for Basic Auth (Used only if AUTH_TYPE is "Basic").  Can be omitted if you aren't using Basic Auth
  BASIC_AUTH_USER: USER_CHANGEME                        # Used for basic auth
  BASIC_AUTH_PASS: PWD_CHANGEME                         # Used for basic auth
  # ENV for OIDC (Used only if AUTH_TYPE is "OIDC").  Can be omitted if you aren't using OIDC
  OIDC_AUTH_URL: https://auth.$DOMAIN/.well-known/openid-configuration # URL for your OIDC issuer's well-known endpoint
  OIDC_CLIENT_ID: headscale-webui                       # Your OIDC Issuer's Client ID for Headscale-WebUI
  OIDC_CLIENT_SECRET: YourSecretHere                    # Your OIDC Issuer's Secret Key for Headscale-WebUI