version: '3'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    networks:
      - proxy_network
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      #- "80:80/tcp"
    volumes:
      - 'pihole_data:/etc/pihole'
      - 'pihole_dnsmasq:/etc/dnsmasq.d'
    # cap_add:
      # - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: $WEBPASSWORD
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.pihole.tls=true"
     - "traefik.http.routers.pihole.rule=Host(`$PUBLIC_HOSTNAME`)"
     - "traefik.http.services.pihole.loadbalancer.server.port=80"
     # add middleware for /admin prefix
     - "traefik.http.middlewares.pihole-admin.addprefix.prefix=/admin"
     - "traefik.http.routers.pihole.middlewares=pihole-admin"
     # exclude /admin from middleware
     - "traefik.http.routers.pihole-admin.rule=Host(`$PUBLIC_HOSTNAME`) && PathPrefix(`/admin`)"
     # - "traefik.http.routers.traefik.tls.certresolver=letsencrypt" # when using tlsChallenge certresolver

volumes:
  pihole_data:
  pihole_dnsmasq:

networks:
  proxy_network:
    name: $PROXY_NETWORK
    external: true