version: v2
teleport:
  nodename: teleport-1
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  cluster_name: $DOMAINNAME
  # enable webauthn support
  authentication:
    type: local
    second_factor: on
    webauthn:
      rp_id: $DOMAINNAME
  # assist:
  #   openai:
  #     api_token_path: /etc/teleport/openai_key

ssh_service:
  enabled: "no"

proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:3080
  public_addr: ['$DOMAINNAME:443']
  https_keypairs: []
  acme: {}

app_service:
  enabled: no
  # enabled: yes
  # apps:
  # - name: "example app"
  #   uri: "http://example-app-url"
  #   insecure_skip_verify: false