apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: docspell
resources:
- ../../base
- ../oidc
patches:
- target:
    kind: Deployment
    name: restserver
  path: patch-restserver.yml
- target:
    kind: StatefulSet
    name: postgres
  path: patch-postgres.yml
- target:
    kind: StatefulSet
    name: solr
  path: patch-solr.yml
