- op: replace
  path: /kind
  value: Deployment
- op: remove
  path: /spec/serviceName
- op: remove
  path: /spec/volumeClaimTemplates
- op: add
  path: /spec/template/spec/volumes
  value:
    - name: postgres-data
      hostPath:
        path: /mnt/pool-raidz2/application-persistent-data/docspell/db
        type: Directory